select =[
"E", # pycodestyle error
"F", # pyflake
"W", # whitespace
"NPY", # numpy
"TID", # tidy-imports
"B", # bugbear
]

ignore = [
"E731", # Do not assign a lambda expression, use a def 
"E741", # Don't use I, O, l as variable names
"F401", # unused import
"B011", # Do not assert False
]

line-length = 100

target-version = "py39" # Minimum jax version

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402"]

